### ISSUE TITLE
ed25519 key error

### ISSUE THREAD

**Issue by rajeevn1** [whitesmith/hawkpost#293] opened 2019-09-30 18:18 UTC
I am unable to use ECC key.  I get invalid key, fingerprint does not match error. Is ECC supported?

**Comment by rajeevn1** [comment] 2019-10-02 17:59
I moved to using https://encrypt.to/

**Comment by dethos** [comment] 2019-10-13 17:17
Just tested with this disposable ECC key:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEXaNaZhYJKwYBBAHaRw8BAQdAsHpdGZJwMeL5Vutbs2VVy5FrKBkyWJD8rcNG
HqBhRae0BXRlc3RliJYEExYIAD4WIQTuupsVWH2OorZ1YtKeIlh1UdIncwUCXaNa
ZgIbAwUJAAD6ygULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRCeIlh1UdInc5OS
AP9v2lPPTff2IAaIRuift75amkAB3CFfIZeQmCczhYW0lgEAyVQ8DhJnz8F7DxnJ
cDMlaAFs4eKufrOk4WRxQRFSpwS4OARdo1pmEgorBgEEAZdVAQUBAQdAnX7ox+KJ
7Y8gbpeVgBYqkC7GT2xryxfzvZo43s0kyT8DAQgHiH4EGBYIACYWIQTuupsVWH2O
orZ1YtKeIlh1UdIncwUCXaNaZgIbDAUJAAD6ygAKCRCeIlh1UdInc2sTAP437pYe
RMmxfjgsRp0X01WZ/MXp2Skza9N85I43vKrVXwD/bItruM6TEiWKBFTtHtq2Zl3e
R9Wt2UV97sBtCCNvIgY=
=hDMZ
-----END PGP PUBLIC KEY BLOCK-----
```
Fingerprint: `EEBA9B15587D8EA2B67562D29E22587551D22773`

I was able to reproduce problem.

Since the project should deal with ECC keys (it would not make sense otherwise), I will re-open the issue.

**Comment by NewRedsquare** [comment] 2020-06-18 21:39
Any progress on this issue ?

**Comment by dethos** [comment] 2020-06-26 22:38
I can't reproduce this problem locally, so it doesn't seem related with `hawkpost` codebase itself. Perhaps `hawkpost.co` is using an outdated/old version of `gnupg`. 

cc: @pjaneiro

**Comment by NewRedsquare** [comment] 2020-11-10 15:53
Any news ?

**Comment by pdcribeiro** [comment] 2020-11-25 18:06
Updated the server. This should be fixed now.

**Closed as completed by pdcribeiro** 2020-11-25 18:06 UTC
Labels: bug, hacktoberfest

**Comment by pdcribeiro** [comment] 2020-12-09 12:05
@dethos, the `gnupg` version that was running on `hawkpost.co` was the same but now I can't reproduce the issue. Can you confirm its fixed?
