### ISSUE TITLE
Error encrypting message

### ISSUE THREAD

**Issue by jmesserli** [whitesmith/hawkpost#185] opened 2016-10-19 13:00 UTC
Hello, 
I tried using hawkpost.co today and was experiencing the following error:

```
openpgp.min.0ac5ae9c7d87.js:8 Uncaught (in promise) Error: Error encrypting message: Could not find valid key packet for encryption in key 3f77ce4377661af7
    at A (https://hawkpost.co/static/javascripts/openpgp.min.0ac5ae9c7d87.js:8:29141)
```

This was happening here: https://hawkpost.co/box/ec362e6c-490f-42a1-9f0e-d04aa7c43378 when I clicked on the `Encrypt and Send` button. (The box should still be open since it `Never expires`.)

My GPG Key fingerprint is `F3140E4A8D56FF55792112EF3F77CE4377661AF7` and I added the key using the keyserver URL https://pgp.mit.edu/pks/lookup?op=get&fingerprint=on&search=0xF3140E4A8D56FF55792112EF3F77CE4377661AF7.

I am assuming this is happening because I signed up using github, where my e-mail address is `hi.github@peg.nu`, but my public key has different e-mail adresses on it. I will probably delete the account and manually sign up with a matching e-mail address, but it might be good to inform users that their public key doesn't match their e-mail.

**Comment by dethos** [comment] 2016-10-19 16:19
This seem to be an OpenPGP issue, but I'm not really sure. I will try to reproduce and dig into what is going on, will post the results here later. Thanks for the detailed description.

**Comment by dpflucas** [comment] 2016-10-24 12:08
This is also happening to me. I can create boxes successfully, but when the sender tries to encrypt the message, the above error occurs.

Note that previously my account was working properly - but now this is happening with all my boxes. I didn't change any of my settings.

**Comment by dpflucas** [comment] 2016-10-25 17:13
It looks like that, in my case, the problem was that my key was already expired. I added a new working key to my hawkpost settings, and it is working again.

Anyhow, there should be some kind of feedback in this situation - for example, do not allow the creation of boxes with expired keys.

**Comment by dethos** [comment] 2016-10-25 17:26
@dpflucas that validation is done daily for users that provide the keyserver url (expiration and revocation), disabling the ability do create new boxes or to submit content to existing boxes. Did you provide the url or only the public key?

Probably we should expand this feature to all keys.

**Comment by dpflucas** [comment] 2016-10-25 17:31
@dethos I provided the url

**Comment by jmesserli** [comment] 2016-10-25 18:29
In my case, the key and all subkeys were valid when the error occurred (It expires on 2017-07-18).

![image](https://cloud.githubusercontent.com/assets/613138/19698966/ad8b0c1e-9af1-11e6-9e58-1a15a7314db6.png)

**Comment by dethos** [comment] 2017-11-23 15:33
Even after the last PR, I was able to replicate the same issue, with a key that had its expiration date extended and seems the same happened with the initial report on this issue. This has been open for too long, will add the priority tag.

**Comment by pdcribeiro** [comment] 2020-11-20 14:27
I can't reproduce this issue. Tried using an expired and renewed key and a key for a different email address but got no errors. Tried both on the production server and on a new setup.

**Comment by pdcribeiro** [comment] 2020-12-10 00:17
@dethos, can you help me here?

**Comment by dethos** [comment] 2020-12-11 18:39
I cannot replicate the issue anymore as well. Since it is so old and there aren't any recent complains lets close the issue. If anything comes up we can re-open.

**Closed as completed by dethos** 2020-12-11 18:39 UTC
Labels: bug, help wanted, prioritary
